- name: Docusaurus S3 Sync
  # You may pin to the exact commit or the version.
  # uses: turnerlabs/s3-docusaurus-sync-action@2a0da8c8cef39d9ba9255b5616db2f339111eebc
  uses: turnerlabs/s3-docusaurus-sync-action@1.0.2
